# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1f\n\x0cjsonImageMsg\x12\x0f\n\x07jsonimg\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\x39\n\x08RawImage\x12-\n\x0eRawImageDimens\x12\x0c.rawImageMsg\x1a\x0b.imageReply\"\x00\x32&\n\x03\x41\x64\x64\x12\x1f\n\x07\x41\x64\x64Nums\x12\x07.addMsg\x1a\t.addReply\"\x00\x32;\n\nDotProduct\x12-\n\x07\x44otProd\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\"\x00\x32<\n\tJsonImage\x12/\n\x0fJsonImageDimens\x12\r.jsonImageMsg\x1a\x0b.imageReply\"\x00\x62\x06proto3'
)




_ADDMSG = _descriptor.Descriptor(
  name='addMsg',
  full_name='addMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='addMsg.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='addMsg.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=47,
)


_RAWIMAGEMSG = _descriptor.Descriptor(
  name='rawImageMsg',
  full_name='rawImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='rawImageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=75,
)


_DOTPRODUCTMSG = _descriptor.Descriptor(
  name='dotProductMsg',
  full_name='dotProductMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='dotProductMsg.a', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='dotProductMsg.b', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=114,
)


_JSONIMAGEMSG = _descriptor.Descriptor(
  name='jsonImageMsg',
  full_name='jsonImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonimg', full_name='jsonImageMsg.jsonimg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=147,
)


_ADDREPLY = _descriptor.Descriptor(
  name='addReply',
  full_name='addReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='addReply.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=172,
)


_DOTPRODUCTREPLY = _descriptor.Descriptor(
  name='dotProductReply',
  full_name='dotProductReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dotproduct', full_name='dotProductReply.dotproduct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=211,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='imageReply',
  full_name='imageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='imageReply.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='imageReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=256,
)

DESCRIPTOR.message_types_by_name['addMsg'] = _ADDMSG
DESCRIPTOR.message_types_by_name['rawImageMsg'] = _RAWIMAGEMSG
DESCRIPTOR.message_types_by_name['dotProductMsg'] = _DOTPRODUCTMSG
DESCRIPTOR.message_types_by_name['jsonImageMsg'] = _JSONIMAGEMSG
DESCRIPTOR.message_types_by_name['addReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['dotProductReply'] = _DOTPRODUCTREPLY
DESCRIPTOR.message_types_by_name['imageReply'] = _IMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addMsg = _reflection.GeneratedProtocolMessageType('addMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:addMsg)
  })
_sym_db.RegisterMessage(addMsg)

rawImageMsg = _reflection.GeneratedProtocolMessageType('rawImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _RAWIMAGEMSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:rawImageMsg)
  })
_sym_db.RegisterMessage(rawImageMsg)

dotProductMsg = _reflection.GeneratedProtocolMessageType('dotProductMsg', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTMSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:dotProductMsg)
  })
_sym_db.RegisterMessage(dotProductMsg)

jsonImageMsg = _reflection.GeneratedProtocolMessageType('jsonImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _JSONIMAGEMSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:jsonImageMsg)
  })
_sym_db.RegisterMessage(jsonImageMsg)

addReply = _reflection.GeneratedProtocolMessageType('addReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:addReply)
  })
_sym_db.RegisterMessage(addReply)

dotProductReply = _reflection.GeneratedProtocolMessageType('dotProductReply', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:dotProductReply)
  })
_sym_db.RegisterMessage(dotProductReply)

imageReply = _reflection.GeneratedProtocolMessageType('imageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:imageReply)
  })
_sym_db.RegisterMessage(imageReply)



_RAWIMAGE = _descriptor.ServiceDescriptor(
  name='RawImage',
  full_name='RawImage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=315,
  methods=[
  _descriptor.MethodDescriptor(
    name='RawImageDimens',
    full_name='RawImage.RawImageDimens',
    index=0,
    containing_service=None,
    input_type=_RAWIMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAWIMAGE)

DESCRIPTOR.services_by_name['RawImage'] = _RAWIMAGE


_ADD = _descriptor.ServiceDescriptor(
  name='Add',
  full_name='Add',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=317,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddNums',
    full_name='Add.AddNums',
    index=0,
    containing_service=None,
    input_type=_ADDMSG,
    output_type=_ADDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADD)

DESCRIPTOR.services_by_name['Add'] = _ADD


_DOTPRODUCT = _descriptor.ServiceDescriptor(
  name='DotProduct',
  full_name='DotProduct',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=357,
  serialized_end=416,
  methods=[
  _descriptor.MethodDescriptor(
    name='DotProd',
    full_name='DotProduct.DotProd',
    index=0,
    containing_service=None,
    input_type=_DOTPRODUCTMSG,
    output_type=_DOTPRODUCTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOTPRODUCT)

DESCRIPTOR.services_by_name['DotProduct'] = _DOTPRODUCT


_JSONIMAGE = _descriptor.ServiceDescriptor(
  name='JsonImage',
  full_name='JsonImage',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=418,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='JsonImageDimens',
    full_name='JsonImage.JsonImageDimens',
    index=0,
    containing_service=None,
    input_type=_JSONIMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JSONIMAGE)

DESCRIPTOR.services_by_name['JsonImage'] = _JSONIMAGE

# @@protoc_insertion_point(module_scope)
